from typing import Any

class Attributes:
    @classmethod
    def is_a_procedure(cls, name: Any): ...
    @classmethod
    def is_a_property_accessor(cls, name: Any): ...
    @classmethod
    def is_a_property_getter(cls, name: Any): ...
    @classmethod
    def is_a_property_setter(cls, name: Any): ...
    @classmethod
    def is_a_class_member(cls, name: Any): ...
    @classmethod
    def is_a_class_method(cls, name: Any): ...
    @classmethod
    def is_a_class_static_method(cls, name: Any): ...
    @classmethod
    def is_a_class_property_accessor(cls, name: Any): ...
    @classmethod
    def is_a_class_property_getter(cls, name: Any): ...
    @classmethod
    def is_a_class_property_setter(cls, name: Any): ...
    @classmethod
    def get_property_name(cls, name: Any): ...
    @classmethod
    def get_class_name(cls, name: Any): ...
    @classmethod
    def get_class_member_name(cls, name: Any): ...
