from typing import Any

class Connection:
    def __init__(self, address: Any, port: Any) -> None: ...
    def connect(self) -> None: ...
    def close(self) -> None: ...
    def __del__(self) -> None: ...
    def send_message(self, message: Any) -> None: ...
    def receive_message(self, typ: Any): ...
    def send(self, data: Any) -> None: ...
    def receive(self, length: Any): ...
    def partial_receive(self, length: Any, timeout: float = ...): ...
