from typing import Any

class Encoder:
    @classmethod
    def encode(cls, x: Any, typ: Any): ...
    @classmethod
    def encode_message_with_size(cls, message: Any): ...

class _ValueEncoder:
    @classmethod
    def encode_double(cls, value: Any): ...
    @classmethod
    def encode_float(cls, value: Any): ...
    @classmethod
    def encode_sint32(cls, value: Any): ...
    @classmethod
    def encode_sint64(cls, value: Any): ...
    @classmethod
    def encode_uint32(cls, value: Any): ...
    @classmethod
    def encode_uint64(cls, value: Any): ...
    @classmethod
    def encode_bool(cls, value: Any): ...
    @classmethod
    def encode_string(cls, value: Any): ...
    @classmethod
    def encode_bytes(cls, value: Any): ...
