from typing import Any, Optional

class Event:
    def __init__(self, conn: Any, event: Any) -> None: ...
    def start(self) -> None: ...
    @property
    def condition(self): ...
    def wait(self, timeout: Optional[Any] = ...) -> None: ...
    def add_callback(self, callback: Any) -> None: ...
    def remove_callback(self, callback: Any) -> None: ...
    @property
    def stream(self): ...
    def remove(self) -> None: ...
